apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: frontend
  name: frontend
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: huzaifa8195/vehicle-frontend:latest
        imagePullPolicy: IfNotPresent
        name: frontend
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /app/data
          name: data-volume
        - mountPath: /usr/share/nginx/html/env-config.js
          name: frontend-config
          subPath: env-config.js
        - mountPath: /usr/share/nginx/html/fetch-override.js
          name: frontend-config
          subPath: fetch-override.js
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-pvc
      - name: frontend-config
        configMap:
          name: frontend-config 