apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: vehicle-app
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: frontend 