name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube's environment
      shell: powershell
      run: |
        echo "Configuring Docker to use Minikube's daemon..."
        # Use PowerShell specific command to set Docker environment
        minikube docker-env --shell powershell | Invoke-Expression

    - name: Build Docker image
      shell: powershell
      run: |
        docker build -t huzaifa8195/vehicle-frontend:latest .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: huzaifa8195
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image to Docker Hub
      shell: powershell
      run: docker push huzaifa8195/vehicle-frontend:latest

    - name: Create vehicle-app namespace if it doesn't exist
      shell: powershell
      run: |
        $namespaceExists = kubectl get namespace vehicle-app 2>$null
        if (-not $?) {
          Write-Host "Namespace vehicle-app does not exist. Creating it..."
          kubectl create namespace vehicle-app
        } else {
          Write-Host "Namespace vehicle-app already exists."
        }

    - name: Deploy to Minikube
      shell: powershell
      run: |
        # Update namespace in deployment files
        (Get-Content k8s/frontend-deployment-new.yaml) -replace 'namespace: default', 'namespace: vehicle-app' | Set-Content k8s/frontend-deployment-new.yaml
        
        # Apply ConfigMap first
        kubectl apply -f k8s/frontend-config.yaml -n vehicle-app
        
        # Apply PVC
        kubectl apply -f k8s/data-pvc.yaml -n vehicle-app
        
        # Apply Deployment
        kubectl apply -f k8s/frontend-deployment-new.yaml -n vehicle-app
        
        # Apply Service
        kubectl apply -f k8s/frontend-service.yaml
        
        # Wait for deployment to be ready
        kubectl rollout status deployment/frontend -n vehicle-app

    - name: Display deployment information
      shell: powershell
      run: |
        Write-Host "=== Pods ===" -ForegroundColor Cyan
        kubectl get pods -n vehicle-app
        
        Write-Host "=== Services ===" -ForegroundColor Cyan
        kubectl get services -n vehicle-app
        
        Write-Host "=== Deployments ===" -ForegroundColor Cyan
        kubectl get deployments -n vehicle-app
        
        Write-Host "=== ConfigMaps ===" -ForegroundColor Cyan
        kubectl get configmaps -n vehicle-app
        
        Write-Host "=== PVCs ===" -ForegroundColor Cyan
        kubectl get pvc -n vehicle-app

    - name: Access application URL
      shell: powershell
      run: |
        Write-Host "To access the application, run the following command:" -ForegroundColor Green
        Write-Host "minikube service frontend -n vehicle-app" -ForegroundColor Yellow
        minikube service frontend -n vehicle-app --url 